// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3gFepDhbdVBaDHe3ms9CNF
// Component: lHrnwZQKsB

import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_fbla_2023_website_design.module.css"; // plasmic-import: 3gFepDhbdVBaDHe3ms9CNF/projectcss
import sty from "./PlasmicTagline.module.css"; // plasmic-import: lHrnwZQKsB/css

export type PlasmicTagline__VariantMembers = {};
export type PlasmicTagline__VariantsArgs = {};
type VariantPropType = keyof PlasmicTagline__VariantsArgs;
export const PlasmicTagline__VariantProps = new Array<VariantPropType>();

export type PlasmicTagline__ArgsType = {
  children?: React.ReactNode;
  slot?: React.ReactNode;
};
type ArgPropType = keyof PlasmicTagline__ArgsType;
export const PlasmicTagline__ArgProps = new Array<ArgPropType>(
  "children",
  "slot"
);

export type PlasmicTagline__OverridesType = {
  headingTagline?: p.Flex<"div">;
  h1?: p.Flex<"h1">;
};

export interface DefaultTaglineProps {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicTagline__RenderFunc(props: {
  variants: PlasmicTagline__VariantsArgs;
  args: PlasmicTagline__ArgsType;
  overrides: PlasmicTagline__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});

  return (
    <div
      data-plasmic-name={"headingTagline"}
      data-plasmic-override={overrides.headingTagline}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.headingTagline
      )}
    >
      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__bHxR)}
      >
        <h1
          data-plasmic-name={"h1"}
          data-plasmic-override={overrides.h1}
          className={classNames(projectcss.all, projectcss.h1, sty.h1)}
        >
          {p.renderPlasmicSlot({
            defaultContents: "Tagline",
            value: args.children,
            className: classNames(sty.slotTargetChildren)
          })}
        </h1>
        <div className={classNames(projectcss.all, sty.freeBox__dK6)}>
          {p.renderPlasmicSlot({
            defaultContents:
              "KingCare is a 501(c)(3) non-profit that provides social services to the socioeconomically disadvantaged of King County. Since our inception in 2014, we have provided for more than 5,000 under-resourced residents and have given back over $400,000 to the community.\n",
            value: args.slot,
            className: classNames(sty.slotTargetSlot)
          })}
        </div>
      </p.Stack>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  headingTagline: ["headingTagline", "h1"],
  h1: ["h1"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  headingTagline: "div";
  h1: "h1";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTagline__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTagline__VariantsArgs;
    args?: PlasmicTagline__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicTagline__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicTagline__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicTagline__ArgProps,
          internalVariantPropNames: PlasmicTagline__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTagline__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "headingTagline") {
    func.displayName = "PlasmicTagline";
  } else {
    func.displayName = `PlasmicTagline.${nodeName}`;
  }
  return func;
}

export const PlasmicTagline = Object.assign(
  // Top-level PlasmicTagline renders the root element
  makeNodeComponent("headingTagline"),
  {
    // Helper components rendering sub-elements
    h1: makeNodeComponent("h1"),

    // Metadata about props expected for PlasmicTagline
    internalVariantProps: PlasmicTagline__VariantProps,
    internalArgProps: PlasmicTagline__ArgProps
  }
);

export default PlasmicTagline;
/* prettier-ignore-end */
